apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: api-gateway-secret
  namespace: gateway
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: erumpay-dev-secret-store
    kind: ClusterSecretStore
  target:
    name: api-gateway-secret
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: erumpay/dev/all
        property: JWT_SECRET
    - secretKey: PG_JWT_SECRET
      remoteRef:
        key: erumpay/dev/all
        property: PG_JWT_SECRET
