apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-service-secret
  namespace: pay
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: erumpay-dev-secret-store
    kind: ClusterSecretStore
  target:
    name: auth-service-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key: erumpay/dev/all
        property: DB_USERNAME
    - secretKey: DB_PASSWORD
      remoteRef:
        key: erumpay/dev/all
        property: DB_PASSWORD
    - secretKey: JWT_SECRET
      remoteRef:
        key: erumpay/dev/all
        property: JWT_SECRET
    - secretKey: AES_SECRET_KEY
      remoteRef:
        key: erumpay/dev/all
        property: AES_SECRET_KEY
    - secretKey: PHONE_HASH_SALT
      remoteRef:
        key: erumpay/dev/all
        property: PHONE_HASH_SALT
    - secretKey: KAKAO_CLIENT_SECRET
      remoteRef:
        key: erumpay/dev/all
        property: AUTH_KAKAO_CLIENT_SECRET
    - secretKey: OCTOMO_API_KEY
      remoteRef:
        key: erumpay/dev/all
        property: OCTOMO_API_KEY
