apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: payment-service-secret
  namespace: pay
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: erumpay-dev-secret-store
    kind: ClusterSecretStore
  target:
    name: payment-service-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key: erumpay/dev/all
        property: DB_USERNAME
    - secretKey: DB_PASSWORD
      remoteRef:
        key: erumpay/dev/all
        property: DB_PASSWORD
