apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pg-payment-service-secret
  namespace: pg
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: erumpay-dev-secret-store
    kind: ClusterSecretStore
  target:
    name: pg-payment-service-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key: erumpay/dev/all
        property: DB_USERNAME
    - secretKey: DB_PASSWORD
      remoteRef:
        key: erumpay/dev/all
        property: DB_PASSWORD
    - secretKey: PG_PAYMENT_RECONCILIATION_AUTHORIZATION
      remoteRef:
        key: erumpay/dev/all
        property: PG_PAYMENT_RECONCILIATION_AUTHORIZATION
