nameOverride: api-gateway
fullnameOverride: api-gateway
replicaCount: 2

image:
  repository: "512138915880.dkr.ecr.ap-northeast-2.amazonaws.com/erumpay/api-gateway"
  tag: "4dd7248"

containerPort: 8080

service:
  port: 8080

env:
  ZIPKIN_ENDPOINT: "http://erumpay-zipkin.platform-operations.svc.cluster.local:9411/api/v2/spans"
  TRACING_SAMPLING_PROBABILITY: "1.0"
  AUTH_SERVICE_URI: "http://auth-service.pay.svc.cluster.local:8081"
  CARD_SERVICE_URI: "http://card-service.pay.svc.cluster.local:8082"
  PAYMENT_SERVICE_URI: "http://payment-service.pay.svc.cluster.local:8083"
  RECOMMENDATION_SERVICE_URI: "http://recommendation-service.pay.svc.cluster.local:8084"
  NOTIFICATION_SERVICE_URI: "http://notification-service.pay.svc.cluster.local:8085"
  PG_AUTH_SERVICE_URI: "http://pg-auth-service.pg.svc.cluster.local:8091"
  BILLING_KEY_SERVICE_URI: "http://billing-key-service.pg.svc.cluster.local:8092"
  PG_PAYMENT_SERVICE_URI: "http://pg-payment-service.pg.svc.cluster.local:8093"
  MERCHANT_SERVICE_URI: "http://merchant-service.pg.svc.cluster.local:8094"
  CARD_SIMULATOR_SERVICE_URI: "http://card-simulator-service.pg.svc.cluster.local:8095"

existingSecret: api-gateway-secret
secretEnv: {}

nodeSelector: {}

ingress:
  enabled: true
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/healthcheck-path: /actuator/health/readiness
    external-dns.alpha.kubernetes.io/hostname: api.eunna.store
  hosts:
    - host: api.eunna.store
  paths:
    - path: /
      pathType: Prefix
  tls:
    - hosts:
        - api.eunna.store
