nameOverride: auth-service
fullnameOverride: auth-service
replicaCount: 2

image:
  repository: "512138915880.dkr.ecr.ap-northeast-2.amazonaws.com/erumpay/auth-service"
  tag: "66cc5ea"

containerPort: 8081

service:
  port: 8081

env:
  ZIPKIN_ENDPOINT: "http://erumpay-zipkin.platform-operations.svc.cluster.local:9411/api/v2/spans"
  TRACING_SAMPLING_PROBABILITY: "1.0"
  DB_URL: "jdbc:mysql://erumpay-mysql.c1i4w0cia7ah.ap-northeast-2.rds.amazonaws.com:3306/auth_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul"
  KAKAO_CLIENT_ID: "3338ab0088875b9e2ba0e4a620d33ae0"
  KAKAO_REDIRECT_URI: "http://localhost:19000/auth/callback"
  REDIS_HOST: "erumpay-redis-master.middleware.svc.cluster.local"
  SCHEMA_REGISTRY_URL: "http://erumpay-schema-registry.middleware.svc.cluster.local:18081"

existingSecret: auth-service-secret
secretEnv: {}

nodeSelector:
  role: pay
