nameOverride: billing-key-service
fullnameOverride: billing-key-service
replicaCount: 2

image:
  repository: "512138915880.dkr.ecr.ap-northeast-2.amazonaws.com/erumpay/billing-key-service"
  tag: "c3c9fc0"

containerPort: 8092

service:
  port: 8092

env:
  ZIPKIN_ENDPOINT: "http://erumpay-zipkin.platform-operations.svc.cluster.local:9411/api/v2/spans"
  TRACING_SAMPLING_PROBABILITY: "1.0"
  DB_URL: "jdbc:mysql://erumpay-mysql.c1i4w0cia7ah.ap-northeast-2.rds.amazonaws.com:3306/pg_billing_db"
  CARD_SIMULATOR_BASE_URL: "http://card-simulator-service:8095"

existingSecret: billing-key-service-secret
secretEnv: {}

nodeSelector:
  role: pg
