nameOverride: card-service
fullnameOverride: card-service
replicaCount: 2

image:
  repository: "<AWS_ACCOUNT_ID>.dkr.ecr.ap-northeast-2.amazonaws.com/card-service"
  tag: latest

containerPort: 8082

service:
  port: 8082

env:
  DB_URL: jdbc:mysql://<RDS_ENDPOINT>:3306/card_db

secretEnv:
  DB_USERNAME: "<DB_USERNAME>"
  DB_PASSWORD: "<DB_PASSWORD>"

nodeSelector:
  role: pay
