nameOverride: card-service
fullnameOverride: card-service
replicaCount: 2

image:
  repository: "512138915880.dkr.ecr.ap-northeast-2.amazonaws.com/erumpay/card-service"
  tag: latest

containerPort: 8082

service:
  port: 8082

env:
  ZIPKIN_ENDPOINT: "http://erumpay-zipkin.platform-operations.svc.cluster.local:9411/api/v2/spans"
  TRACING_SAMPLING_PROBABILITY: "1.0"
  DB_URL: "jdbc:mysql://erumpay-mysql.c1i4w0cia7ah.ap-northeast-2.rds.amazonaws.com:3306/card_db"
  AUTH_SERVICE_BASE_URL: "http://auth-service:8081"
  BILLING_KEY_SERVICE_BASE_URL: "http://billing-key-service.pg.svc.cluster.local:8092"
  KAFKA_BOOTSTRAP_SERVERS: "erumpay-kafka.middleware.svc.cluster.local:29092"

existingSecret: card-service-secret
secretEnv: {}

nodeSelector:
  role: pay
