nameOverride: merchant-service
fullnameOverride: merchant-service
replicaCount: 2

image:
  repository: "<AWS_ACCOUNT_ID>.dkr.ecr.ap-northeast-2.amazonaws.com/merchant-service"
  tag: latest

containerPort: 8094

service:
  port: 8094

env:
  DB_URL: jdbc:mysql://<RDS_ENDPOINT>:3306/pg_merchant_db

secretEnv:
  DB_USERNAME: "<DB_USERNAME>"
  DB_PASSWORD: "<DB_PASSWORD>"

nodeSelector:
  role: pg
