nameOverride: notification-service
fullnameOverride: notification-service
replicaCount: 2

image:
  repository: "512138915880.dkr.ecr.ap-northeast-2.amazonaws.com/erumpay/notification-service"
  tag: "bb8d094"

containerPort: 8085

service:
  port: 8085

env:
  ZIPKIN_ENDPOINT: "http://erumpay-zipkin.platform-operations.svc.cluster.local:9411/api/v2/spans"
  TRACING_SAMPLING_PROBABILITY: "1.0"
  DB_URL: "jdbc:mysql://erumpay-mysql.c1i4w0cia7ah.ap-northeast-2.rds.amazonaws.com:3306/notification_db"
  KAFKA_BOOTSTRAP_SERVERS: "erumpay-kafka.middleware.svc.cluster.local:9092"
  AUTH_BASE_URL: "http://auth-service:8081"

existingSecret: notification-service-secret
secretEnv: {}

nodeSelector:
  role: pay
