nameOverride: payment-service
fullnameOverride: payment-service
replicaCount: 2

image:
  repository: "512138915880.dkr.ecr.ap-northeast-2.amazonaws.com/erumpay/payment-service"
  tag: "ee22321"

containerPort: 8083

service:
  port: 8083

env:
  ZIPKIN_ENDPOINT: "http://erumpay-zipkin.platform-operations.svc.cluster.local:9411/api/v2/spans"
  TRACING_SAMPLING_PROBABILITY: "1.0"
  DB_URL: "jdbc:mysql://erumpay-mysql.c1i4w0cia7ah.ap-northeast-2.rds.amazonaws.com:3306/payment_db"
  QR_BASEURL: "http://localhost:8083/qr?token="
  AUTH_BASE_URL: "http://auth-service.pay.svc.cluster.local:8081"
  RECOMMEND_BASE_URL: "http://recommendation-service.pay.svc.cluster.local:8084/"
  CARD_BASE_URL: "http://card-service:8082"
  PG_BASE_URL: "http://pg-payment-service.pg.svc.cluster.local:8093/"
  MERCHANT_BASE_URL: "http://merchant-service.pg.svc.cluster.local:8094/"
  KAFKA_BOOTSTRAP_SERVERS: "erumpay-kafka.middleware.svc.cluster.local:9092"
  SCHEMA_REGISTRY_URL: "http://erumpay-schema-registry.middleware.svc.cluster.local:18081"
  REDIS_HOST: "erumpay-redis-master.middleware.svc.cluster.local"
  REDIS_PORT: "6379"
  PG_AUTHORIZATION: "Bearer server-test-token"

  CHECKOUT_REDIRECT_BASE_URL: "http://localhost:19000/payment/method-select?token="

  REMOTE_PAY_FRIEND_VALIDATION_ENABLED: "true"

  PAYMENT_EVENT_TOPIC: "payment.event"
  DUTCH_EVENT_TOPIC: "dutch.event"
  REMOTE_COMMAND_TOPIC: "remote.command"
  REMOTE_EVENT_TOPIC: "remote.event"

existingSecret: payment-service-secret
secretEnv: {}

nodeSelector:
  role: pay

ingress:
  enabled: false
  hosts:
    - host: api.dev.erumpay.com
  paths:
    - path: /api/v1/payment
      pathType: Prefix
    - path: /api/v1/dutch-pay
      pathType: Prefix
    - path: /internal/v1/dutch-pay
      pathType: Prefix
    - path: /qr
      pathType: Prefix
