-- ErumPay recommend_db merchant keyword override seed
-- source: used_brand_names from card_gorilla seed dry-run
-- scope: representative brand names only; alias table is intentionally out of MVP scope.
-- note: recommendation-service must normalize whitespace/punctuation/case before comparing merchant names and keywords.
-- note: when multiple keywords match, choose priority DESC, then normalized keyword length DESC, before MCC fallback.
-- priority: 1000 + normalized keyword length. More specific merchant keywords must win over broader parent keywords.

SET NAMES utf8mb4;
USE recommend_db;

START TRANSACTION;

INSERT INTO recommend_merchant_keyword_override (
  keyword,
  override_category,
  priority,
  created_at,
  is_active
)
VALUES
  ('11번가', 'SHOPPING', 1004, NOW(), TRUE),
  ('CGV', 'LEISURE', 1003, NOW(), TRUE),
  ('CU', 'CVS', 1002, NOW(), TRUE),
  ('GS 수퍼마켓', 'GROCERY', 1006, NOW(), TRUE),
  ('GS25', 'CVS', 1004, NOW(), TRUE),
  ('GS칼텍스', 'AUTO', 1005, NOW(), TRUE),
  ('G마켓', 'SHOPPING', 1003, NOW(), TRUE),
  ('HD현대오일뱅크', 'AUTO', 1008, NOW(), TRUE),
  ('KT', 'TELECOM', 1002, NOW(), TRUE),
  ('LG U+', 'TELECOM', 1004, NOW(), TRUE),
  ('LOHB''s', 'BEAUTY', 1006, NOW(), TRUE),
  ('NOL 티켓', 'LEISURE', 1005, NOW(), TRUE),
  ('S-OIL', 'AUTO', 1004, NOW(), TRUE),
  ('SKT', 'TELECOM', 1003, NOW(), TRUE),
  ('SK에너지', 'AUTO', 1005, NOW(), TRUE),
  ('SSG.COM', 'SHOPPING', 1006, NOW(), TRUE),
  ('VIPS', 'FOOD', 1004, NOW(), TRUE),
  ('Y_MART', 'GROCERY', 1005, NOW(), TRUE),
  ('교원', 'EDU', 1002, NOW(), TRUE),
  ('네이버플러스 멤버십', 'ETC', 1009, NOW(), TRUE),
  ('네이버플러스 스토어', 'SHOPPING', 1009, NOW(), TRUE),
  ('넷플릭스', 'ETC', 1004, NOW(), TRUE),
  ('다이소', 'SHOPPING', 1003, NOW(), TRUE),
  ('대교', 'EDU', 1002, NOW(), TRUE),
  ('대성마이맥', 'EDU', 1005, NOW(), TRUE),
  ('디즈니+', 'ETC', 1004, NOW(), TRUE),
  ('디즈니플러스', 'ETC', 1006, NOW(), TRUE),
  ('땡겨요', 'FOOD', 1003, NOW(), TRUE),
  ('뚜레쥬르', 'FOOD', 1004, NOW(), TRUE),
  ('롯데마트', 'GROCERY', 1004, NOW(), TRUE),
  ('롯데마트 맥스', 'GROCERY', 1006, NOW(), TRUE),
  ('롯데백화점', 'SHOPPING', 1005, NOW(), TRUE),
  ('롯데슈퍼', 'GROCERY', 1004, NOW(), TRUE),
  ('롯데시네마', 'LEISURE', 1005, NOW(), TRUE),
  ('롯데월드', 'LEISURE', 1004, NOW(), TRUE),
  ('롯데프리미엄아울렛', 'SHOPPING', 1009, NOW(), TRUE),
  ('마켓컬리', 'SHOPPING', 1004, NOW(), TRUE),
  ('매머드커피', 'CAFE', 1005, NOW(), TRUE),
  ('메가마트', 'GROCERY', 1004, NOW(), TRUE),
  ('메가박스', 'LEISURE', 1004, NOW(), TRUE),
  ('메가스터디', 'EDU', 1005, NOW(), TRUE),
  ('메가스터디교육', 'EDU', 1007, NOW(), TRUE),
  ('메가커피', 'CAFE', 1004, NOW(), TRUE),
  ('멜론', 'ETC', 1002, NOW(), TRUE),
  ('밀크T', 'EDU', 1003, NOW(), TRUE),
  ('배달의 민족', 'FOOD', 1005, NOW(), TRUE),
  ('빽다방', 'CAFE', 1003, NOW(), TRUE),
  ('삼성카드 쇼핑', 'SHOPPING', 1006, NOW(), TRUE),
  ('세븐일레븐', 'CVS', 1005, NOW(), TRUE),
  ('스타벅스', 'CAFE', 1004, NOW(), TRUE),
  ('시코르', 'BEAUTY', 1003, NOW(), TRUE),
  ('신세계백화점', 'SHOPPING', 1006, NOW(), TRUE),
  ('신세계사이먼', 'SHOPPING', 1006, NOW(), TRUE),
  ('아웃백', 'FOOD', 1003, NOW(), TRUE),
  ('알라딘', 'LEISURE', 1003, NOW(), TRUE),
  ('에버랜드', 'LEISURE', 1004, NOW(), TRUE),
  ('엔제리너스', 'CAFE', 1005, NOW(), TRUE),
  ('엘리하이', 'EDU', 1004, NOW(), TRUE),
  ('엠베스트', 'EDU', 1004, NOW(), TRUE),
  ('영암마트', 'GROCERY', 1004, NOW(), TRUE),
  ('옥션', 'SHOPPING', 1002, NOW(), TRUE),
  ('올리브영', 'BEAUTY', 1004, NOW(), TRUE),
  ('와인앤모어', 'ETC', 1005, NOW(), TRUE),
  ('왓챠', 'ETC', 1002, NOW(), TRUE),
  ('요기요', 'FOOD', 1003, NOW(), TRUE),
  ('웅진씽크빅', 'EDU', 1005, NOW(), TRUE),
  ('웨이브', 'ETC', 1003, NOW(), TRUE),
  ('유튜브', 'ETC', 1003, NOW(), TRUE),
  ('이디야', 'CAFE', 1003, NOW(), TRUE),
  ('이마트', 'GROCERY', 1003, NOW(), TRUE),
  ('이마트 에브리데이', 'GROCERY', 1008, NOW(), TRUE),
  ('이마트24', 'CVS', 1005, NOW(), TRUE),
  ('이케아', 'SHOPPING', 1003, NOW(), TRUE),
  ('이투스', 'EDU', 1003, NOW(), TRUE),
  ('지니뮤직', 'ETC', 1004, NOW(), TRUE),
  ('천재교과서', 'EDU', 1005, NOW(), TRUE),
  ('커피빈', 'CAFE', 1003, NOW(), TRUE),
  ('컬리', 'SHOPPING', 1002, NOW(), TRUE),
  ('컴포즈커피', 'CAFE', 1005, NOW(), TRUE),
  ('쿠팡', 'SHOPPING', 1002, NOW(), TRUE),
  ('쿠팡 와우 멤버십', 'ETC', 1007, NOW(), TRUE),
  ('쿠팡이츠', 'FOOD', 1004, NOW(), TRUE),
  ('투썸플레이스', 'CAFE', 1006, NOW(), TRUE),
  ('트레이더스 홀세일 클럽', 'GROCERY', 1010, NOW(), TRUE),
  ('티빙', 'ETC', 1002, NOW(), TRUE),
  ('파리바게뜨', 'FOOD', 1005, NOW(), TRUE),
  ('폴바셋', 'CAFE', 1003, NOW(), TRUE),
  ('한솔교육', 'EDU', 1004, NOW(), TRUE),
  ('할리스', 'CAFE', 1003, NOW(), TRUE),
  ('현대백화점', 'SHOPPING', 1005, NOW(), TRUE),
  ('현대오일뱅크', 'AUTO', 1006, NOW(), TRUE),
  ('현대프리미엄아울렛', 'SHOPPING', 1009, NOW(), TRUE),
  ('홈플러스', 'GROCERY', 1004, NOW(), TRUE),
  ('홈플러스 익스프레스', 'GROCERY', 1009, NOW(), TRUE)
ON DUPLICATE KEY UPDATE
  override_category = VALUES(override_category),
  priority = VALUES(priority),
  is_active = VALUES(is_active);

COMMIT;
